# Generated by Django 2.1.5 on 2019-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190206_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='logimg/%Y/%m %d', width_field='width_field'),
        ),
    ]
