# Generated by Django 2.0.10 on 2019-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20190206_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='logimg', width_field='width_field'),
        ),
    ]

    
