# Generated by Django 2.0.10 on 2019-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20190206_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='log',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logimg'),
        ),
    ]
